export const stripeCountry = [
  // { name: 'Australia', country_code: 'AU', currency_code: 'AUD' },
  // { name: 'Austria', country_code: 'AT', currency_code: 'EUR' },
  // { name: 'Belgium', country_code: 'BE', currency_code: 'EUR' },
  // { name: 'Brazil ', country_code: 'BR', currency_code: 'BRL' },
  // { name: 'Canada', country_code: 'CA', currency_code: 'CAD' },
  // { name: 'Cyprus', country_code: 'CY', currency_code: 'EUR' },
  // { name: 'Denmark', country_code: 'DK', currency_code: 'DKK' },
  // { name: 'Estonia', country_code: 'EE', currency_code: 'EUR' },
  // { name: 'Finland', country_code: 'FI', currency_code: 'EUR' },
  // { name: 'France', country_code: 'FR', currency_code: 'EUR' },
  // { name: 'Germany', country_code: 'DE', currency_code: 'EUR' },
  // { name: 'Greece', country_code: 'GR', currency_code: 'EUR' },
  // { name: 'Hong Kong', country_code: 'HK', currency_code: 'HKD' },
  // { name: 'India', country_code: 'IN', currency_code: 'INR' },
  // { name: 'Ireland', country_code: 'IE', currency_code: 'EUR' },
  // { name: 'Italy', country_code: 'IT', currency_code: 'EUR' },
  // { name: 'Japan', country_code: 'JP', currency_code: 'JPY' },
  // { name: 'Latvia', country_code: 'LV', currency_code: 'LVL' },
  // { name: 'Lithuania', country_code: 'LT', currency_code: 'LTL' },
  // { name: 'Luxembourg', country_code: 'LU', currency_code: 'EUR' },
  // { name: 'Malaysia ', country_code: 'MY', currency_code: 'MYR' },
  // { name: 'Malta ', country_code: 'MT', currency_code: 'EUR' },
  // { name: 'Mexico ', country_code: 'MX', currency_code: 'MXN' },
  // { name: 'Netherlands', country_code: 'NL', currency_code: 'EUR' },
  // { name: 'New Zealand', country_code: 'NZ', currency_code: 'NZD' },
  // { name: 'Norway', country_code: 'NO', currency_code: 'NOK' },
  // { name: 'Poland', country_code: 'PL', currency_code: 'PLN' },
  // { name: 'Portugal', country_code: 'PT', currency_code: 'EUR' },
  // { name: 'Romania', country_code: 'RO', currency_code: 'RON' },
  // { name: 'Singapore', country_code: 'SG', currency_code: 'SGD' },
  // { name: 'Slovakia', country_code: 'SK', currency_code: 'EUR' },
  // { name: 'Slovenia', country_code: 'SI', currency_code: 'EUR' },
  // { name: 'Spain', country_code: 'ES', currency_code: 'EUR' },
  // { name: 'Sweden', country_code: 'SE', currency_code: 'SEK' },
  // { name: 'Switzerland', country_code: 'CH', currency_code: 'CHF' },
  // { name: 'United Kingdom', country_code: 'GB', currency_code: 'GBP' },
  { name: 'United States', country_code: 'US', currency_code: 'USD' },
];

export const CANADA_STATE = [
  {
    name: 'Alberta',
    state_code: 'AB',
  },
  {
    name: 'British Columbia',
    state_code: 'BC',
  },
  {
    name: 'Manitoba',
    state_code: 'MB',
  },
  {
    name: 'New Brunswick',
    state_code: 'NB',
  },
  {
    name: 'Newfoundland and Labrador',
    state_code: 'NL',
  },
  {
    name: 'Nova Scotia',
    state_code: 'NS',
  },
  {
    name: 'Northwest Territories',
    state_code: 'NT',
  },
  {
    name: 'Nunavut',
    state_code: 'NU',
  },
  {
    name: 'Ontario',
    state_code: 'ON',
  },
  {
    name: 'Prince Edward Island',
    state_code: 'PE',
  },
  {
    name: 'Québec',
    state_code: 'QC',
  },
  {
    name: 'Saskatchewan',
    state_code: 'SK',
  },
  {
    name: 'Yukon',
    state_code: 'YT',
  },
];

export const US_STATES = [
  {
    name: 'Alabama',
    state_code: 'AL',
  },
  {
    name: 'Alaska',
    state_code: 'AK',
  },
  {
    name: 'American Samoa',
    state_code: 'AS',
  },
  {
    name: 'Arizona',
    state_code: 'AZ',
  },
  {
    name: 'Arkansas',
    state_code: 'AR',
  },
  {
    name: 'California',
    state_code: 'CA',
  },
  {
    name: 'Colorado',
    state_code: 'CO',
  },
  {
    name: 'Connecticut',
    state_code: 'CT',
  },
  {
    name: 'Delaware',
    state_code: 'DE',
  },
  {
    name: 'District Of Columbia',
    state_code: 'DC',
  },
  {
    name: 'Federated States Of Micronesia',
    state_code: 'FM',
  },
  {
    name: 'Florida',
    state_code: 'FL',
  },
  {
    name: 'Georgia',
    state_code: 'GA',
  },
  {
    name: 'Guam Gu',
    state_code: 'GU',
  },
  {
    name: 'Hawaii',
    state_code: 'HI',
  },
  {
    name: 'Idaho',
    state_code: 'ID',
  },
  {
    name: 'Illinois',
    state_code: 'IL',
  },
  {
    name: 'Indiana',
    state_code: 'IN',
  },
  {
    name: 'Iowa',
    state_code: 'IA',
  },
  {
    name: 'Kansas',
    state_code: 'KS',
  },
  {
    name: 'Kentucky',
    state_code: 'KY',
  },
  {
    name: 'Louisiana',
    state_code: 'LA',
  },
  {
    name: 'Maine',
    state_code: 'ME',
  },
  {
    name: 'Marshall Islands',
    state_code: 'MH',
  },
  {
    name: 'Maryland',
    state_code: 'MD',
  },
  {
    name: 'Massachusetts',
    state_code: 'MA',
  },
  {
    name: 'Michigan',
    state_code: 'MI',
  },
  {
    name: 'Minnesota',
    state_code: 'MN',
  },
  {
    name: 'Mississippi',
    state_code: 'MS',
  },
  {
    name: 'Missouri',
    state_code: 'MO',
  },
  {
    name: 'Montana',
    state_code: 'MT',
  },
  {
    name: 'Nebraska',
    state_code: 'NE',
  },
  {
    name: 'Nevada',
    state_code: 'NV',
  },
  {
    name: 'New Hampshire',
    state_code: 'NH',
  },
  {
    name: 'New Jersey',
    state_code: 'NJ',
  },
  {
    name: 'New Mexico',
    state_code: 'NM',
  },
  {
    name: 'New York',
    state_code: 'NY',
  },
  {
    name: 'North Carolina',
    state_code: 'NC',
  },
  {
    name: 'North Dakota',
    state_code: 'ND',
  },
  {
    name: 'Northern Mariana Islands',
    state_code: 'MP',
  },
  {
    name: 'Ohio',
    state_code: 'OH',
  },
  {
    name: 'Oklahoma',
    state_code: 'OK',
  },
  {
    name: 'Oregon',
    state_code: 'OR',
  },
  {
    name: 'Palau',
    state_code: 'PW',
  },
  {
    name: 'Pennsylvania',
    state_code: 'PA',
  },
  {
    name: 'Puerto Rico',
    state_code: 'PR',
  },
  {
    name: 'Rhode Island',
    state_code: 'RI',
  },
  {
    name: 'South Carolina',
    state_code: 'SC',
  },
  {
    name: 'South Dakota',
    state_code: 'SD',
  },
  {
    name: 'Tennessee',
    state_code: 'TN',
  },
  {
    name: 'Texas',
    state_code: 'TX',
  },
  {
    name: 'Utah',
    state_code: 'UT',
  },
  {
    name: 'Vermont',
    state_code: 'VT',
  },
  {
    name: 'Virgin Islands',
    state_code: 'VI',
  },
  {
    name: 'Virginia',
    state_code: 'VA',
  },
  {
    name: 'Washington',
    state_code: 'WA',
  },
  {
    name: 'West Virginia',
    state_code: 'WV',
  },
  {
    name: 'Wisconsin',
    state_code: 'WI',
  },
  {
    name: 'Wyoming',
    state_code: 'WY',
  },
];

export const country = [
  'United States',
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo, Republic of the',
  'Congo, Democratic Republic of the',
  'Costa Rica',
  'Ivory Coast',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'North Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'St. Kitts and Nevis ',
  'St. Lucia',
  'St. Vincent and The Grenadines ',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe ',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

export const monthList = [
  { value: '1', label: 'January' },
  { value: '2', label: 'February' },
  { value: '3', label: 'March' },
  { value: '4', label: 'April' },
  { value: '5', label: 'May' },
  { value: '6', label: 'June' },
  { value: '7', label: 'July' },
  { value: '8', label: 'August' },
  { value: '9', label: 'September' },
  { value: '10', label: 'October' },
  { value: '11', label: 'November' },
  { value: '12', label: 'December' },
];

export const yearList = [
  { value: '2020', label: '2020' },
  { value: '2021', label: '2021' },
  { value: '2022', label: '2022' },
  { value: '2023', label: '2023' },
  { value: '2024', label: '2024' },
  { value: '2025', label: '2025' },
  { value: '2026', label: '2026' },
  { value: '2027', label: '2027' },
  { value: '2028', label: '2028' },
  { value: '2029', label: '2029' },
  { value: '2030', label: '2030' },
  { value: '2031', label: '2031' },
  { value: '2032', label: '2032' },
  { value: '2033', label: '2033' },
  { value: '2034', label: '2034' },
  { value: '2035', label: '2035' },
  { value: '2036', label: '2036' },
  { value: '2037', label: '2037' },
  { value: '2038', label: '2038' },
  { value: '2039', label: '2039' },
  { value: '2040', label: '2040' },
  { value: '2041', label: '2041' },
  { value: '2042', label: '2042' },
  { value: '2043', label: '2043' },
  { value: '2044', label: '2044' },
  { value: '2045', label: '2045' },
];

export const phoneOptions = [
  { label: 'USA (+1)', value: '+1' },
  { label: 'Japan (+81)', value: '+81' },
  { label: 'France (+33)', value: '+33' },
  { label: 'UK (+44)', value: '+44' },
  { label: 'India (+91)', value: '+91' },
];

export const VideoFormats = ['video/mp4'];
export const ImageFormats = ['image/jpg', 'image/jpeg', 'image/gif', 'image/png'];
export const MIN_FILE_SIZE = 8000;

